[package]
name = "stress"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
mongodb = "3.2"
regex = "1.11"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }
