services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: "0.375"
          memory: "750M"

  server1:
    build: .
    container_name: server1
    depends_on:
      - mongodb
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.375"
          memory: "750M"

  server2:
    build: .
    container_name: server2
    depends_on:
      - mongodb
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.375"
          memory: "750M"

  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server1
      - server2
    deploy:
      resources:
        limits:
          cpus: "0.375"
          memory: "750M"

volumes:
  mongo_data:
