services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "750M"

  server1:
    container_name: server1
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - mongodb
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "1075M"

  server2:
    container_name: server2
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - mongodb
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "1075M"

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - server1
      - server2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "100M"
